#!/bin/sh

#This script removes automatically trailing whitespaces at end of line
#Thanks XCode for all those when using Cmd+I  by the way!
#Don't forget to make it executable chmod a+x .git/hooks/pre-commit
#It can be bypassed using git commit --no-verify

if git rev-parse --verify HEAD >/dev/null 2>&1 ; then
   against=HEAD
else
   # Initial commit: diff against an empty tree object
   against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Find files with trailing whitespace
(
IFS='
'
FILES=`exec git diff-index --check --cached $against -- | sed '/^[+-]/d' | sed -E 's/:[0-9]+:.*//' | uniq`

for FILE in $FILES ; do
    echo Removing trailing whitespace in "$FILE"
    sed -i '' -E 's/[[:space:]]*$//' "$FILE"
    git add "$FILE"
done
)

